# Site
title: ixBand.js
subtitle: ixBnad.js Documentation
description: ixBnad.js Documentation
author: blaxk
language: ko
date_format: '%Y-%m-%d'

# URL
url:
baseurl: '/ixband'
permalink: /:path/

# Conversion
markdown:    kramdown
highlighter: rouge

# Default
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/



# Plugins
## Docs: https://help.github.com/articles/configuring-jekyll-plugins/
plugins:
 - jekyll-sitemap




# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash (/archives -> archives)
menu:
  home: /
  docs: /docs/
  download: /download/
  #categories: /categories/
  #about: /about/
  #tags: /tags/
  #sitemap: /sitemap.xml


# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# Algolia Search
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"


# Local search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1