# Site
title: ixBand.js
subtitle: ixBnad.js Documentation
description: ixBnad.js Documentation
author: blaxk
language: ko
date_format: '%Y-%m-%d'
timezone: 'Asia/Seoul'

# URL
url: http://ixband.org
baseurl: /
permalink: /:path/

# Conversion
markdown:    kramdown
highlighter: rouge

collections:
  docs:
    output: true
    permalink: /docs/:path/

# Default
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
  -
    scope:
      path: 'docs'
      type: 'docs'
    values:
      layout: 'docs'
