# Site
title: ixBand.js
subtitle: ixBnad.js Documentation
description: ixBnad.js Documentation
author: blaxk
language: ko
date_format: '%Y-%m-%d'
timezone: 'Asia/Seoul'

# URL
url:
baseurl: '/ixband'
permalink: /:path/

# Conversion
markdown:    kramdown
highlighter: rouge

# Default
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'default'
  -
    scope:
      path: 'docs'
      type: 'pages'
    values:
      layout: 'docs'
      category: 'docs'



# Plugins
## Docs: https://help.github.com/articles/configuring-jekyll-plugins/
plugins:
 - jekyll-sitemap


# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------

# Algolia Search
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"


# Local search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1